### ISSUE TITLE
Telif hakkında

### ISSUE THREAD

**Issue by kadorek** [melihsakarya/java-kitap#1]
Merhaba Melih bey,

Derslerimde, hazırlamış olduğunuz java notlarını kullansam bir sıkıntı olur mu?

**Comment by melihsakarya** [comment]
kullanabilirsiniz tabiiki hiç bir sıkıntı olmaz

23 Mar 2021 Sal 15:24 tarihinde kadorek ***@***.***> şunu
yazdı:

**Comment by kadorek** [comment]
Teşekkür ederim
